import axios from 'axios';
import Head from 'next/head';
import { useForm } from 'react-hook-form';
import { useRouter } from 'next/router';

export default function Index() {
  const router = useRouter();
  const { register, handleSubmit } = useForm();
  const onSubmit = async (data) => {
    await axios
      .post('/api/auth/login', data)
      .then((res) => {
        if (res.status === 200) {
          router.push('/home');
          console.log(res);
        }
      })
      .catch((err) => {
        console.log(err);
      });
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full flex flex-col items-center justify-center border border-green-200 min-h-screen ">
        <h1 className="text-6xl text-red-500 ">AUTH</h1>
        <form
          onSubmit={handleSubmit(onSubmit)}
          className=" flex flex-col justify-center align-center"
        >
          <div className="space-x-3">
            <input className="input" {...register('username', { required: true })} />
            <input className="input" type="password" {...register('psw', { required: true })} />
          </div>
          <button className="button mt-5" type="submit">
            Login
          </button>
        </form>
      </div>
    </div>
  );
}
